
FROM golang:1.18.3-alpine3.16 AS builder
WORKDIR /app
# COPY go.mod .
# COPY go.sum .
# RUN go mod download
COPY . .
RUN go mod tidy
RUN go build -o order_api
 
FROM alpine:3.13
WORKDIR /app 
COPY --from=builder /app/order_api .
COPY config.yaml .

EXPOSE 8080
CMD ["/app/order_api"]

