FROM golang:1.18.3-alpine3.16 AS builder
WORKDIR /app
# COPY go.mod .
# COPY go.sum .
# RUN go mod download
COPY . .
RUN go mod tidy
RUN go build -o store_api
 
FROM alpine:3.13
WORKDIR /app 
COPY --from=builder /app/store_api .
COPY config.yaml .

EXPOSE 4000
CMD ["/app/store_api"]
